Clearning up mnist.py and generate_image.py
Very surprised that this does not work in data/mnist.py:
55  #images = np.fromfile(f, dtype=np.uint8).reshape(size, rows, cols)
Compared to:
56  image_data = array("B", f.read())
57  images = np.array(image_data).reshape(size, rows, cols)

The error I get is:
images = np.fromfile(f, dtype='uint8').reshape(size, rows, cols)
ValueError: cannot reshape array of size 9912406 into shape (60000,28,28)

which is a factor of around 4.7~ less data than needed.